### PR TITLE
feat: add maintainers.md

### LINKED ISSUE #2: Add MAINTAINERS.md file
Please duplicate the file in https://raw.githubusercontent.com/open-horizon-services/web-helloworld-cpp/ac403917069c896f685a317f4ca6b503694f5187/MAINTAINERS.md in this repo.

### PR DESCRIPTION
**Pull request by retry19**
Closes #2 

## New Changes

- Added MAINTAINERS.md file

### CODE REVIEW

**Review by joewxboy — CHANGES_REQUESTED** [review]
Thanks, @retry19 , it looks like the file was created properly.  However, you did not "sign" your commit.  Could you please go back and amend your commit to add the sign-off?

**Comment by retry19** [comment]
> Thanks, @retry19 , it looks like the file was created properly. However, you did not "sign" your commit. Could you please go back and amend your commit to add the sign-off?

I wasn't aware of it, wait ya, fixing...

**Comment by retry19** [comment]
@joewxboy I already sign my commit

**Review by joewxboy — APPROVED** [review]

**Comment by joewxboy** [comment]
Congratulations, Reza.  You are now officially a project Contributor.

**Comment by retry19** [comment]
> Congratulations, Reza. You are now officially a project Contributor.

Thanks @joewxboy 😁

**Pull request merged**
